### ISSUE TITLE
BuildingManager

### ISSUE THREAD

**Issue by maartenpeels** [maartenpeels/TribalWarsBot#1]
This Building Manager should be instantiated by each village. It will only do stuff for "it's" village.

## Tasks

- [x] Setup a strategy (PurplePredator?)
- [x] Figure out next building to upgrade (if any)
- [x] Check resource requirements
- [x] Execute order
